# Standard libraries

In [287]:
import os
import pandas as pd

# Read in 2025 Predictions

In [288]:
espn_f = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\2025_espn_predictions.csv"
afl_f = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\afl_website_2025.csv"
betfair_f = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\betfair_2025.csv"
bonus_team_f = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\bonus_player_team_map.csv"

In [289]:
espn = pd.read_csv(espn_f)
afl = pd.read_csv(afl_f)
betfair = pd.read_csv(betfair_f)
bonus_team = pd.read_csv(bonus_team_f)

# Read in 2025 game list

In [290]:
teams_f = r"C:\Users\mrjay\python\jupyter_notebooks\Projects\brownlow\data\team_stats_2018_2025_fitzroy.csv"
teams = pd.read_csv(teams_f)

# Normalize Dataframes

## Normalize ESPN

In [291]:
espn_cols_to_keep = ['PLAYER', 'OR', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6',
       'R7', 'R8', 'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16',
       'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23', 'R24']

afl_round_map = {'OR':'round_0', 'R1':'round_1', 'R2':'round_2', 'R3':'round_3', 'R4':'round_4', 'R5':'round_5', 'R6':'round_6', 'R7':'round_7', 'R8':'round_8', 'R9':'round_9', 'R10':'round_10', 'R11':'round_11',
                  'R12':'round_12', 'R13':'round_13', 'R14':'round_14', 'R15':'round_15', 'R16':'round_16', 'R17':'round_17', 'R18':'round_18', 'R19':'round_19', 'R20':'round_20', 'R21':'round_21', 'R22':'round_22', 'R23':'round_23', 'R24':'round_24'}

In [292]:
espn_subset = espn.loc[:,espn_cols_to_keep]

In [293]:
espn_subset = espn_subset.rename(columns=afl_round_map)

In [294]:
espn_subset.head()

,PLAYER,round_0,round_1,round_2,round_3,round_4,round_5,round_6,round_7,round_8,...,round_15,round_16,round_17,round_18,round_19,round_20,round_21,round_22,round_23,round_24
0,NICK DAICOS,-,2,2.5,-,1,2,3,0.5,0.5,...,2,2.5,3,-,1.5,3,-,-,2.5,-
1,BAILEY SMITH,-,3,-,-,1,2,2,1.5,2,...,-,-,-,-,-,2,1.5,2.5,2,3
2,NOAH ANDERSON,-,3,-,1.5,-,1.5,1,-,-,...,2,-,2,1.5,-,2.5,3,-,0.5,2.5
3,JORDAN DAWSON,-,3,2.5,-,0.5,-,2,-,2.5,...,-,2.5,0.5,1,-,-,3,3,-,-
4,MARCUS BONTEMPELLI,-,-,-,-,-,-,3,2,1.5,...,3,-,1,2,-,3,1.5,0.5,3,3

In [295]:
espn_long = espn_subset.melt(id_vars=['PLAYER'], var_name='ROUND_ID', value_name='VOTES')

In [296]:
espn_long.head()

               PLAYER ROUND_ID VOTES
0         NICK DAICOS  round_0     -
1        BAILEY SMITH  round_0     -
2       NOAH ANDERSON  round_0     -
3       JORDAN DAWSON  round_0     -
4  MARCUS BONTEMPELLI  round_0     -

## Normalize AFL

In [297]:
# add PLAYER column
afl['PLAYER'] = (afl['firstName'] + " " + afl['surname']).str.upper()

In [298]:
afl_player_to_team = afl.loc[:,['PLAYER','teamId']]

In [299]:
afl_cols_to_keep = ['PLAYER','round_0','round_1','round_2','round_3','round_4','round_5','round_6','round_7','round_8','round_9','round_10','round_11','round_12','round_13','round_14','round_15','round_16',
                    'round_17','round_18','round_19','round_20','round_21','round_22','round_23','round_24']

In [300]:
afl_subset = afl.loc[:,afl_cols_to_keep]

In [301]:
afl_subset

,PLAYER,round_0,round_1,round_2,round_3,round_4,round_5,round_6,round_7,round_8,...,round_15,round_16,round_17,round_18,round_19,round_20,round_21,round_22,round_23,round_24
0,JORDAN DAWSON,0.0,3.0,3.0,0.0,1.0,0.0,3.0,0.0,3.0,...,0.0,3.0,0.0,1.0,0.0,0.0,3.0,3.0,1.0,0.0
1,NICK DAICOS,0.0,0.0,3.0,0.0,0.0,2.0,3.0,0.0,2.0,...,3.0,2.0,3.0,0.0,3.0,3.0,0.0,0.0,3.0,0.0
2,BAILEY SMITH,0.0,3.0,0.0,0.0,0.0,3.0,2.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,2.0,1.0,3.0,3.0,3.0
3,NOAH ANDERSON,0.0,3.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,...,2.0,0.0,3.0,2.0,0.0,2.0,3.0,0.0,0.0,3.0
4,HUGH MCCLUGGAGE,0.0,0.0,0.0,3.0,2.0,2.0,0.0,0.0,2.0,...,0.0,0.0,2.0,0.0,2.0,0.0,3.0,0.0,2.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,JAXON PRIOR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
804,JAY POLKINGHORNE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
805,JAYDEN HUNT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
806,JAYDEN LAVERDE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
807,ZANE ZAKOSTELSKY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [302]:
afl_long = afl_subset.melt(id_vars='PLAYER',var_name='ROUND_ID', value_name='VOTES')

In [303]:
afl

,Unnamed: 0,firstName,surname,teamId,round_0,round_1,round_2,round_3,round_4,round_5,...,round_19,round_20,round_21,round_22,round_23,round_24,round_25,round_26,total_votes,PLAYER
0,0,Jordan,Dawson,1,0.0,3.0,3.0,0.0,1.0,0.0,...,0.0,0.0,3.0,3.0,1.0,0.0,0.0,0.0,32.0,JORDAN DAWSON
1,1,Nick,Daicos,3,0.0,0.0,3.0,0.0,0.0,2.0,...,3.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,31.0,NICK DAICOS
2,2,Bailey,Smith,10,0.0,3.0,0.0,0.0,0.0,3.0,...,0.0,2.0,1.0,3.0,3.0,3.0,0.0,0.0,31.0,BAILEY SMITH
3,3,Noah,Anderson,4,0.0,3.0,0.0,2.0,0.0,1.0,...,0.0,2.0,3.0,0.0,0.0,3.0,0.0,0.0,30.0,NOAH ANDERSON
4,4,Hugh,McCluggage,2,0.0,0.0,0.0,3.0,2.0,2.0,...,2.0,0.0,3.0,0.0,2.0,3.0,0.0,0.0,28.0,HUGH MCCLUGGAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,803,Jaxon,Prior,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAXON PRIOR
804,804,Jay,Polkinghorne,10,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAY POLKINGHORNE
805,805,Jayden,Hunt,18,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN HUNT
806,806,Jayden,Laverde,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN LAVERDE
807,807,Zane,Zakostelsky,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ZANE ZAKOSTELSKY

## Normalize betfair

In [304]:
betfair = betfair.rename(columns={'player_name':'PLAYER','team':'TEAM'})
betfair['PLAYER'] = betfair['PLAYER'].str.upper()
betfair['TEAM'] = betfair['TEAM'].str.upper()

In [305]:
betfair_player_to_team = betfair[['PLAYER','TEAM']]

In [306]:
betfair_cols_to_keep = ['PLAYER','round_0', 'round_1', 'round_2',
       'round_3', 'round_4', 'round_5', 'round_6', 'round_7', 'round_8',
       'round_9', 'round_10', 'round_11', 'round_12', 'round_13', 'round_14',
       'round_15', 'round_16', 'round_17', 'round_18', 'round_19', 'round_20',
       'round_21', 'round_22', 'round_23', 'round_24']

In [307]:
betfair_subset = betfair.loc[:,betfair_cols_to_keep]

In [308]:
betfair_long = betfair_subset.melt(id_vars='PLAYER',var_name='ROUND_ID', value_name='VOTES')

In [309]:
betfair_long

              PLAYER  ROUND_ID  VOTES
0        NICK DAICOS   round_0    0.0
1      NOAH ANDERSON   round_0    0.0
2       BAILEY SMITH   round_0    0.0
3       CALEB SERONG   round_0    0.0
4      JORDAN DAWSON   round_0    0.0
...              ...       ...    ...
5670    DARCY PARISH  round_24    0.0
5671        NAT FYFE  round_24    0.0
5672     LUKE PARKER  round_24    0.0
5673      MASON WOOD  round_24    0.0
5674  JORDAN DE GOEY  round_24    0.0

[5675 rows x 3 columns]

## Team ID mapping

In [310]:
player_to_team_merge = afl_player_to_team.merge(betfair_player_to_team)
player_to_team_merge.head()

            PLAYER  teamId         TEAM
0    JORDAN DAWSON       1     ADELAIDE
1      NICK DAICOS       3  COLLINGWOOD
2     BAILEY SMITH      10      GEELONG
3    NOAH ANDERSON       4   GOLD COAST
4  HUGH MCCLUGGAGE       2     BRISBANE

In [311]:
team_crosstab = pd.crosstab(player_to_team_merge['teamId'], player_to_team_merge['TEAM'])
team_crosstab

TEAM,ADELAIDE,BRISBANE,CARLTON,COLLINGWOOD,ESSENDON,FREMANTLE,GEELONG,GOLD COAST,GREATER WESTERN SYDNEY,HAWTHORN,MELBOURNE,NORTH MELBOURNE,PORT ADELAIDE,RICHMOND,ST. KILDA,SYDNEY,UNKNOWN,WEST COAST,WESTERN BULLDOGS
teamId,,,,,,,,,,,,,,,,,,,
1,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,10,0,0,0,0,0,0,0,0,0,0,0
5,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,1,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,8,0,0,0,2,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,12
9,0,0,0,0,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,2,0,0
11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,0,2,0,0
12,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,3,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,1,0,0
14,0,0,0,0,0,12,0,0,0,0,0,0,0,0,0,0,2,0,0
15,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,2,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,2,0,0
17,0,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,4,0

In [312]:
team_max_count = team_crosstab.max(axis=1).to_frame('max_count')
team_max_match = team_crosstab.idxmax(axis=1).to_frame('max_match')
team_max_combo = pd.concat([team_max_count, team_max_match], axis=1)

In [313]:
team_max_combo.sort_values(by='max_count')

        max_count               max_match
teamId
18              4              WEST COAST
6               6         NORTH MELBOURNE
16              7                RICHMOND
7               8           PORT ADELAIDE
5               9                 CARLTON
17              9               MELBOURNE
10              9                 GEELONG
12              9                ESSENDON
4              10              GOLD COAST
13             10                  SYDNEY
3              11             COLLINGWOOD
15             11  GREATER WESTERN SYDNEY
14             12               FREMANTLE
1              12                ADELAIDE
8              12        WESTERN BULLDOGS
2              12                BRISBANE
11             12               ST. KILDA
9              14                HAWTHORN

In [314]:
espn_long

                 PLAYER  ROUND_ID VOTES
0           NICK DAICOS   round_0     -
1          BAILEY SMITH   round_0     -
2         NOAH ANDERSON   round_0     -
3         JORDAN DAWSON   round_0     -
4    MARCUS BONTEMPELLI   round_0     -
..                  ...       ...   ...
820        LACHIE NEALE  round_24     -
821        JAI NEWCOMBE  round_24     -
822      PATRICK CRIPPS  round_24     -
823      JEREMY CAMERON  round_24     1
824        JOSH DUNKLEY  round_24   1.5

[825 rows x 3 columns]

In [315]:
afl_long

                 PLAYER  ROUND_ID  VOTES
0         JORDAN DAWSON   round_0    0.0
1           NICK DAICOS   round_0    0.0
2          BAILEY SMITH   round_0    0.0
3         NOAH ANDERSON   round_0    0.0
4       HUGH MCCLUGGAGE   round_0    0.0
...                 ...       ...    ...
20195       JAXON PRIOR  round_24    0.0
20196  JAY POLKINGHORNE  round_24    0.0
20197       JAYDEN HUNT  round_24    0.0
20198    JAYDEN LAVERDE  round_24    0.0
20199  ZANE ZAKOSTELSKY  round_24    0.0

[20200 rows x 3 columns]

In [316]:
# check if any player exists in more than one team
# looks ok to me!!
afl.groupby(['PLAYER'])['teamId'].nunique().sort_values(ascending=False)

PLAYER
AARON CADMAN         1
MAX HALL             1
MATTAES PHILLIPOU    1
MATTHEW CARROLL      1
MATTHEW COTTRELL     1
                    ..
JACK CRISP           1
JACK DARLING         1
JACK DELEAN          1
JACK GINNIVAN        1
ZANE ZAKOSTELSKY     1
Name: teamId, Length: 808, dtype: int64

# Line up player with the team

In [317]:
team_id_map = {'ADELAIDE':'Adelaide Crows','BRISBANE':'Brisbane Lions','COLLINGWOOD':'Collingwood','GOLD COAST':'Gold Coast SUNS','CARLTON':'Carlton','NORTH MELBOURNE':'North Melbourne','PORT ADELAIDE':'Port Adelaide',''
'WESTERN BULLDOGS':'Western Bulldogs','HAWTHORN':'Hawthorn','GEELONG':'Geelong Cats','ST. KILDA':'St Kilda','ESSENDON':'Essendon','SYDNEY':'Sydney Swans','FREMANTLE':'Fremantle','GREATER WESTERN SYDNEY':'GWS GIANTS',
'RICHMOND':'Richmond','MELBOURNE':'Melbourne','WEST COAST':'West Coast Eagles'}

In [318]:
reversed_team_id_map = {
    'Adelaide Crows': 'ADELAIDE',
    'Brisbane Lions': 'BRISBANE',
    'Collingwood': 'COLLINGWOOD',
    'Gold Coast SUNS': 'GOLD COAST',
    'Carlton': 'CARLTON',
    'North Melbourne': 'NORTH MELBOURNE',
    'Port Adelaide': 'PORT ADELAIDE',
    'Western Bulldogs': 'WESTERN BULLDOGS',
    'Hawthorn': 'HAWTHORN',
    'Geelong Cats': 'GEELONG',
    'St Kilda': 'ST. KILDA',
    'Essendon': 'ESSENDON',
    'Sydney Swans': 'SYDNEY',
    'Fremantle': 'FREMANTLE',
    'GWS GIANTS': 'GREATER WESTERN SYDNEY',
    'Richmond': 'RICHMOND',
    'Melbourne': 'MELBOURNE',
    'West Coast Eagles': 'WEST COAST'
}

In [319]:
teams_by_round = teams[teams["round.year"] == 2025]

In [320]:
teams_by_round = teams_by_round[['matchId','match.homeTeam.name','match.awayTeam.name','round.name']]
teams_by_round.loc[:,'round.name'] = teams_by_round.loc[:,'round.name'].str.lower().str.replace(' ','_')
teams_by_round['round.name'] = teams_by_round['round.name'].replace('opening_round', 'round_0')

In [321]:
teams_by_round['home_team'] = teams_by_round['match.homeTeam.name'].map(reversed_team_id_map)
teams_by_round['away_team'] = teams_by_round['match.awayTeam.name'].map(reversed_team_id_map)

In [322]:
teams_by_round.sample(n=3)

,matchId,match.homeTeam.name,match.awayTeam.name,round.name,home_team,away_team
86,CD_M20250141007,Richmond,North Melbourne,round_10,RICHMOND,NORTH MELBOURNE
70,CD_M20250140809,Brisbane Lions,Gold Coast SUNS,round_8,BRISBANE,GOLD COAST
9,CD_M20250140108,Melbourne,GWS GIANTS,round_1,MELBOURNE,GREATER WESTERN SYDNEY

# Line up Predictions

## [1] ESPN

In [323]:
espn_prediction = (espn_long
 .merge(afl[['PLAYER','teamId']])
 .merge(team_max_combo.reset_index())
 .drop(columns=['teamId','max_count'])
 .assign(VOTES=lambda df: pd.to_numeric(df['VOTES'].replace('-', '0'), errors='coerce'))
)

In [324]:
espn_prediction_wide = pd.concat([espn_prediction.merge(teams_by_round, left_on=['max_match','ROUND_ID'], right_on=['home_team','round.name']),
           espn_prediction.merge(teams_by_round, left_on=['max_match','ROUND_ID'], right_on=['away_team','round.name'])])

In [325]:
# SET ROUND 24 to 0 - to avoid double count
espn_prediction_wide.loc[(espn_prediction_wide["matchId"] == 'CD_M20250142401') & (espn_prediction_wide['max_match'] == 'GOLD COAST'), 'VOTES'] = 0

## [2] Betfair

In [327]:
betfair_long['PLAYER'] = betfair_long['PLAYER'].str.strip()

In [328]:
# add in some stragglers
big_player_team_df = pd.concat([afl[['PLAYER','teamId']], bonus_team])

In [329]:
betfair_prediction = (betfair_long
 .merge(big_player_team_df)
 .merge(team_max_combo.reset_index())
 .drop(columns=['teamId','max_count'])
 .assign(VOTES=lambda df: pd.to_numeric(df['VOTES'].replace('-', '0'), errors='coerce'))
)

In [332]:
betfair_long.groupby(['PLAYER'])['VOTES'].sum()

PLAYER
AARON CADMAN          5.5
AARON NAUGHTON        7.5
ADAM CERRA            1.5
ADAM TRELOAR          0.0
ALEX NEALE-BULLEN     5.0
                     ...
WILLIE RIOLI          1.0
ZAC BAILEY            8.5
ZACH GUTHRIE          1.0
ZACH MERRETT         14.0
ZAK BUTTERS          22.0
Name: VOTES, Length: 227, dtype: float64

In [330]:
betfair_prediction['VOTES'].sum()

1224.5

In [331]:
betfair_long['VOTES'].sum()

1239.0

In [282]:
afl[['PLAYER','teamId']]

               PLAYER  teamId
0       JORDAN DAWSON       1
1         NICK DAICOS       3
2        BAILEY SMITH      10
3       NOAH ANDERSON       4
4     HUGH MCCLUGGAGE       2
..                ...     ...
803       JAXON PRIOR      12
804  JAY POLKINGHORNE      10
805       JAYDEN HUNT      18
806    JAYDEN LAVERDE      12
807  ZANE ZAKOSTELSKY       2

[808 rows x 2 columns]

In [268]:
bonus_team[bonus_team["PLAYER"].str.contains('HOGAN')].iloc[0,0]

'JESSE HOGAN'

In [283]:
betfair_merge_attempt = betfair_long.merge(big_player_team_df, how='outer', on='PLAYER', indicator=True)

In [284]:
betfair_merge_attempt['_merge'].value_counts()

_merge
both          5600
right_only     612
left_only      200
Name: count, dtype: int64

In [286]:
betfair_merge_attempt.query("_merge == 'left_only'").groupby('PLAYER')['VOTES'].sum().sort_values(ascending=False)

PLAYER
LUKE DAVIES UNIACKE    9.5
JASON HORNE FRANCIS    8.5
JAKE SOLIGIO           8.0
ALEX NEALE-BULLEN      5.0
JAEGAR O'MEARA         2.0
LACHIE SCHULZ          2.0
PARTICK LIPINSKI       1.0
PETER LADAMS           1.0
Name: VOTES, dtype: float64

In [259]:
afl

,Unnamed: 0,firstName,surname,teamId,round_0,round_1,round_2,round_3,round_4,round_5,...,round_19,round_20,round_21,round_22,round_23,round_24,round_25,round_26,total_votes,PLAYER
0,0,Jordan,Dawson,1,0.0,3.0,3.0,0.0,1.0,0.0,...,0.0,0.0,3.0,3.0,1.0,0.0,0.0,0.0,32.0,JORDAN DAWSON
1,1,Nick,Daicos,3,0.0,0.0,3.0,0.0,0.0,2.0,...,3.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,31.0,NICK DAICOS
2,2,Bailey,Smith,10,0.0,3.0,0.0,0.0,0.0,3.0,...,0.0,2.0,1.0,3.0,3.0,3.0,0.0,0.0,31.0,BAILEY SMITH
3,3,Noah,Anderson,4,0.0,3.0,0.0,2.0,0.0,1.0,...,0.0,2.0,3.0,0.0,0.0,3.0,0.0,0.0,30.0,NOAH ANDERSON
4,4,Hugh,McCluggage,2,0.0,0.0,0.0,3.0,2.0,2.0,...,2.0,0.0,3.0,0.0,2.0,3.0,0.0,0.0,28.0,HUGH MCCLUGGAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,803,Jaxon,Prior,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAXON PRIOR
804,804,Jay,Polkinghorne,10,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAY POLKINGHORNE
805,805,Jayden,Hunt,18,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN HUNT
806,806,Jayden,Laverde,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN LAVERDE
807,807,Zane,Zakostelsky,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ZANE ZAKOSTELSKY

In [199]:
betfair_merge_attempt['_merge'].value_counts()

_merge
both          4975
left_only      700
right_only     609
Name: count, dtype: int64

In [191]:
betfair_prediction['VOTES'].sum()

1144.0

In [97]:
teams['round.year'].unique()

array([2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018], dtype=int64)

In [72]:
teams.loc[:,'round.name'].unique()

array(['Opening Round', 'Round 1', 'Round 2', 'Round 3', 'Round 4',
       'Round 5', 'Round 6', 'Round 7', 'Round 8', 'Round 9', 'Round 10',
       'Round 11', 'Round 12', 'Round 13', 'Round 14', 'Round 15',
       'Round 16', 'Round 17', 'Round 18', 'Round 19', 'Round 20',
       'Round 21', 'Round 22', 'Round 23', 'Round 24', 'Finals Week 1',
       'Semi Finals', 'Preliminary Finals', 'Grand Final'], dtype=object)

In [66]:
afl

,Unnamed: 0,firstName,surname,teamId,round_0,round_1,round_2,round_3,round_4,round_5,...,round_19,round_20,round_21,round_22,round_23,round_24,round_25,round_26,total_votes,PLAYER
0,0,Jordan,Dawson,1,0.0,3.0,3.0,0.0,1.0,0.0,...,0.0,0.0,3.0,3.0,1.0,0.0,0.0,0.0,32.0,JORDAN DAWSON
1,1,Nick,Daicos,3,0.0,0.0,3.0,0.0,0.0,2.0,...,3.0,3.0,0.0,0.0,3.0,0.0,0.0,0.0,31.0,NICK DAICOS
2,2,Bailey,Smith,10,0.0,3.0,0.0,0.0,0.0,3.0,...,0.0,2.0,1.0,3.0,3.0,3.0,0.0,0.0,31.0,BAILEY SMITH
3,3,Noah,Anderson,4,0.0,3.0,0.0,2.0,0.0,1.0,...,0.0,2.0,3.0,0.0,0.0,3.0,0.0,0.0,30.0,NOAH ANDERSON
4,4,Hugh,McCluggage,2,0.0,0.0,0.0,3.0,2.0,2.0,...,2.0,0.0,3.0,0.0,2.0,3.0,0.0,0.0,28.0,HUGH MCCLUGGAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
803,803,Jaxon,Prior,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAXON PRIOR
804,804,Jay,Polkinghorne,10,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAY POLKINGHORNE
805,805,Jayden,Hunt,18,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN HUNT
806,806,Jayden,Laverde,12,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JAYDEN LAVERDE
807,807,Zane,Zakostelsky,2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ZANE ZAKOSTELSKY

In [94]:
teams.loc[:,['match.homeTeam.name']].drop_duplicates().to_clipboard()