In [1]:
import urllib.request, json
import pandas as pd

In [4]:
def get_json(url):
    with urllib.request.urlopen(url) as resp:
        return json.load(resp)

In [6]:
brownlow_data_betfair = get_json("https://betfair-data-supplier-prod.herokuapp.com/api/brownlow?year=2025&widget=brownlow")

In [9]:
selection_df = pd.json_normalize(brownlow_data_betfair)

In [10]:
votes_df = pd.json_normalize(brownlow_data_betfair, record_path='votes', meta=['selection_id','name'])

ValueError: Conflicting metadata name selection_id, need distinguishing prefix

In [11]:
selection_df

,selection_id,name,votes,total,team.id,team.name,team.nickname,team.abbreviation,team.silk,team.created_at,team.updated_at
0,1.8393713,Ollie Wines,"[{'year': '2025', 'selection_id': '1.8393713',...",4.0,13,Port Adelaide,Power,PORT,port,2018-03-27T04:08:47.039Z,2018-03-27T04:08:47.039Z
1,1.000000001016,Nasiah Wanganeen-Milera,"[{'round_number': 1, 'selection_id': '1.000000...",19.0,15,St. Kilda,Saints,STK,stk,2018-03-27T04:08:47.043Z,2018-03-27T04:08:47.043Z
2,1.5416911,Cameron Guthrie,"[{'year': '2025', 'selection_id': '1.5416911',...",0.0,19,Unknown,Unknown,UNK,unk,2018-03-27T04:08:47.052Z,2018-03-27T04:08:47.052Z
3,1.5345945,Dion Prestia,"[{'year': '2025', 'selection_id': '1.5345945',...",2.0,19,Unknown,Unknown,UNK,unk,2018-03-27T04:08:47.052Z,2018-03-27T04:08:47.052Z
4,1.12440308,Tim Taranto,"[{'year': '2025', 'selection_id': '1.12440308'...",13.5,14,Richmond,Tigers,RICH,rich,2018-03-27T04:08:47.042Z,2018-03-27T04:08:47.042Z
...,...,...,...,...,...,...,...,...,...,...,...
221,1.02924074357402347907,Shannon Neale,"[{'round_number': 1, 'selection_id': '1.029240...",2.0,7,Geelong,Cats,GEEL,geel,2018-03-27T04:08:47.026Z,2018-03-27T04:08:47.026Z
222,1.0292407435740323423,Peter Ladams,"[{'round_number': 1, 'selection_id': '1.029240...",1.0,16,Sydney,Swans,SYD,syd,2018-03-27T04:08:47.046Z,2018-03-27T04:08:47.046Z
223,1.0292407435740234705,Darcy Wilson,"[{'round_number': 1, 'selection_id': '1.029240...",1.0,15,St. Kilda,Saints,STK,stk,2018-03-27T04:08:47.043Z,2018-03-27T04:08:47.043Z
224,1.0292407435740231237012470,Alex Pearce,"[{'round_number': 1, 'selection_id': '1.029240...",1.0,6,Fremantle,Dockers,FRE,fre,2018-03-27T04:08:47.024Z,2018-03-27T04:08:47.024Z
225,1.0292407435740234688,Tom Papley,"[{'round_number': 1, 'selection_id': '1.029240...",2.0,16,Sydney,Swans,SYD,syd,2018-03-27T04:08:47.046Z,2018-03-27T04:08:47.046Z

In [12]:
selection_df.loc[0,'votes']

[{'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 1},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '1',
  'dnp': '0',
  'bye': '0',
  'round_number': 2},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '2',
  'dnp': '0',
  'bye': '0',
  'round_number': 3},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 4},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 5},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 6},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 7},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 8},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 9},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 10},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 11},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 12},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 13},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 14},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 15},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 16},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 17},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '1',
  'dnp': '0',
  'bye': '0',
  'round_number': 18},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 19},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 20},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 21},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 22},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 23},
 {'year': '2025',
  'name': 'Ollie Wines',
  'selection_id': '1.8393713',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 24},
 {'year': '2025',
  'selection_id': '1.8393713',
  'name': 'Ollie Wines',
  'vote': '0',
  'dnp': '0',
  'bye': '0',
  'round_number': 0}]

In [13]:
votes_df = pd.json_normalize(selection_df['votes'].explode().dropna().tolist())

In [14]:
votes_df

      year           selection_id         name vote  dnp  bye  round_number
0     2025              1.8393713  Ollie Wines    0    0    0             1
1     2025              1.8393713  Ollie Wines    1    0    0             2
2     2025              1.8393713  Ollie Wines    2    0    0             3
3     2025              1.8393713  Ollie Wines    0    0    0             4
4     2025              1.8393713  Ollie Wines    0    0    0             5
...    ...                    ...          ...  ...  ...  ...           ...
5645   NaN  1.0292407435740234688          NaN  NaN  NaN  NaN            21
5646   NaN  1.0292407435740234688          NaN  NaN  NaN  NaN            22
5647   NaN  1.0292407435740234688          NaN  NaN  NaN  NaN            23
5648  2025  1.0292407435740234688   Tom Papley   02    0    0            24
5649   NaN  1.0292407435740234688          NaN  NaN  NaN  NaN            25

[5650 rows x 7 columns]

In [15]:
votes_df.query("name == 'Nick Daicos'")

      year selection_id         name vote dnp bye  round_number
1525  2025   1.41831043  Nick Daicos  1.5   0   0             1
1526  2025   1.41831043  Nick Daicos    3   0   0             2
1527  2025   1.41831043  Nick Daicos    0   0   0             3
1528  2025   1.41831043  Nick Daicos    0   0   0             4
1529  2025   1.41831043  Nick Daicos    2   0   0             5
1530  2025   1.41831043  Nick Daicos    3   0   0             6
1531  2025   1.41831043  Nick Daicos    0   0   0             7
1532  2025   1.41831043  Nick Daicos    1   0   0             8
1533  2025   1.41831043  Nick Daicos    0   0   0             9
1534  2025   1.41831043  Nick Daicos    1   0   0            10
1535  2025   1.41831043  Nick Daicos    3   0   0            11
1536  2025   1.41831043  Nick Daicos  2.5   0   0            12
1537  2025   1.41831043  Nick Daicos    0   0   0            13
1538  2025   1.41831043  Nick Daicos    0   0   0            14
1539  2025   1.41831043  Nick Daicos  2.5   0   0            15
1540  2025   1.41831043  Nick Daicos  1.5   0   0            16
1541  2025   1.41831043  Nick Daicos    3   0   0            17
1542  2025   1.41831043  Nick Daicos    0   0   0            18
1543  2025   1.41831043  Nick Daicos  1.5   0   0            19
1544  2025   1.41831043  Nick Daicos    3   0   0            20
1545  2025   1.41831043  Nick Daicos    0   0   0            21
1546  2025   1.41831043  Nick Daicos    0   0   0            22
1547  2025   1.41831043  Nick Daicos  0.5   0   0            23
1548  2025   1.41831043  Nick Daicos    2   0   0            24
1549  2025   1.41831043  Nick Daicos    0   0   0             0